### ISSUE TITLE
Project distribution and Namespace naming

### ISSUE THREAD

**Issue by maSchoeller** [maSchoeller/JimnyTainment#5]
# Project distribution
General distribution of the application into 4 projects:
- **JimnyTainment.UI.View**
_The project contains the actual user interface._
- **JimnyTainment.UI.ViewModel**
_Contains the control logic for the user interface._
- **JimnyTainment.Lib**
_Contains various services that are used by the control logic, e.g. analysis classes of autometadata or configuration management, etc..._
  - JimnyTainment.Lib.Analysis
  - JimnyTainment.Lib.Storage
  - JimnyTainment.Lib.Logging

- **JimnyTainment.Drivers**
_Contains various drivers used by the services and ViewModels_
  - JimnyTainment.Drivers.OBD2
  - JimnyTainment.Drivers.Audio
  - JimnyTainment.Drivers.IO
  - JimnyTainment.Drivers.Camera

![Architecture_Namespace](https://user-images.githubusercontent.com/56505280/69151782-9b6dc780-0adb-11ea-9c21-d9611eb418ca.png)

In general this would be an Arichtetcure proposal for project. This proposal would not blow up the application too much, but still divide it up well.

@langmario @pafinkbeiner 
If you still have namespaces you want to add you can simply write them into the issue or what you think about it/how you would do it;)

**Comment by langmario** [comment]
toll

**Comment by langmario** [comment]
german please

**Comment by langmario** [comment]
With this message I herebly confim to you my approval for the given namespaces.
