### ISSUE TITLE
Defining the features

### ISSUE THREAD

**Issue by maSchoeller** [maSchoeller/JimnyTainment#6]
### Audio Support 
- Input over USB/Internal Storage(like playlists)/jack connection/bluetooth?
- Connecting with spotify?
- Ouput over car speakers

### OBD 2 Support
- read the most important data: _Speed, RPM, temperature, oil temperature_

### GPS and Map Support
- With  GPS Module or sim card.
- It is used to support maps navigation systems.
- Possible import of offline maps or use of online maps via a sim map?

### Logging fuel consumption
- provides an overview of fuel consumption and costs
- Adding new tank fillings with costs

### Rear view camera with distance sensors
- assistance system for reverse driving and parking

### Sim card and internet support
- Adds the possibility for web researches
- sending meta data to remote Server
- alternative use the internet connection via your smartphone

|Name|Difficulty for implementation|Value|Depending on|
|---|---|---|---|
|Audio|+|+++||
|OBD2|++|++||
|Maps|+|+++|Internet*|
|Fuel|-|+++||
|Assistance system|++|+++||
|Internet|0|++||

*Only for online maps, but offline maps are more difficult.

What other features do you have in mind?
 What else would you like to have?

**Comment by langmario** [comment]
With this message I herebly confim to you my approval for the given features.
